version: "3.8"

services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "5000:3000"
        environment:
            - NODE_ENV=development
        volumes:
            - ./backend:/app
            - /app/node_modules
        command: npm run start:dev

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - NODE_ENV=development
        volumes:
            - ./frontend:/app
            - /app/node_modules
        command: npm start

    database:
        image: mongo:latest
        container_name: mongo_db
        ports:
            - "27017:27017"
        volumes:
            - mongo_data:/data/db

volumes:
    mongo_data:
